min_version = "2025.1.0"

[tools]
bun = "latest"
clang = "latest"
cmake = "latest"
go = "latest"
github-cli = "latest"
neovim = "latest"
ninja = "latest"
node = "lts"
odin = "latest"
ripgrep = "latest"
rust = "latest"
swift = { version = "latest", os = ["linux", "macos"] }
tree-sitter = "latest"
typst = "latest"
uv = "latest"
zig = "latest"

[settings]
not_found_auto_install = true
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
